apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai
  namespace: sai
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: sai
  template:
    metadata:
      labels:
        app: sai
        pod-name: nginx  # Setting the pod name to "nginx"
    spec:
      containers:
      - name: sai
        image: your-new-image  # Update this with your Docker image name
        ports:
        - containerPort: 80  # Port exposed by the container
---
apiVersion: v1
kind: Service
metadata:
  name: sai-service
  namespace: sai
spec:
  type: NodePort
  selector:
    app: sai
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port to forward traffic to in the pod
      nodePort: 30000  # NodePort for accessing the service externally (you can choose any available port)
